Exercise 5
TimWooSoftwire/DevOps-Course-Starter pull request #5
Opened 2020-09-18 15:55 UTC by TimWooSoftwire

Exercise 5. Haven't done the stretch tasks - will try to have a go next week if I get time!

2020-09-24 10:48 UTC, hugh-emerson requested changes
Generally good, but you need to fix the README with instructions to start a development container, and make sure that when you change a file, that is reflected in the dev instance of your app running in Docker, without rebuilding/restarting it.

I've also left some other small comments.

2020-09-24 10:48 UTC, hugh-emerson commented on Dockerfile
> +COPY . /app
You are copying files into the image for both prod and dev. This means that you do not get the benefit of hot reloading as you change files during dev - you would need to rebuild the image and start a new container.

The exercise brief asks you to mount a volume for the dev image instead.

2020-09-24 10:48 UTC, hugh-emerson commented on Dockerfile
> +FROM python:3.9.0rc2-buster as base
Bit surprising to use a release candidate version of Python rather than a stable release, but should be fine

2020-09-24 10:48 UTC, hugh-emerson commented on README.md
> +docker run --env-file .env -p 5000:5000 todo-app:prod
You forgot to change your dev instructions from a copy of the prod ones.

2020-09-24 10:48 UTC, hugh-emerson commented on wsgi.py
> +from app import app
This will need to be updated after you merge in exercise-3

2020-09-24 10:48 UTC, hugh-emerson commented on Dockerfile
> +FROM base as production
You can also set production specific config here
E.g. `ENV FLASK_ENV=production`

2020-09-24 10:48 UTC, hugh-emerson commented on Dockerfile
> +RUN poetry install
There's a `--no-dev` option for skipping packages in the dev-dependencies section of your toml file. Useful for production

2020-10-09 14:02 UTC, TimWooSoftwire commented
Markups are here!

2020-10-19 10:24 UTC, hugh-emerson commented
Looks good! 👍

2020-10-19 12:22 UTC, merged