Exercise 7
TimWooSoftwire/DevOps-Course-Starter pull request #7
Opened 2020-12-18 12:38 UTC by TimWooSoftwire

2020-12-18 12:43 UTC, TimWooSoftwire commented
Exercise 7 - see exciting All checks have passed above!

2021-01-08 13:52 UTC, Jonesey13 requested changes
While the travis build looks OK the test container does not work locally following the instructions in the `README.md` file (essentially because the `.env.test` file have an incorrect environment variable).

Could you please correct `README.md` and resubmit.

2021-01-08 13:52 UTC, Jonesey13 commented on .travis.yml
> +  - FLASK_SKIP_DOTENV=true DONT_CHECK_FOR_TRELLO_LIST_IDS=true
These are never passed to the test container (and if they were the tests would fail because `DONT_CHECK_FOR_TRELLO_LIST_IDS` needs to be false for the e2e tests to work)

2021-01-08 13:52 UTC, Jonesey13 commented on Dockerfile
> +FROM base as production
Moving this here effectively stops the dockerfile from becoming a multi-stage build

2021-01-08 13:52 UTC, Jonesey13 commented on README.md
> +docker run --env.file .env.test my-test-image tests
This doesn't work locally as `DONT_CHECK_FOR_TRELLO_LIST_IDS` defaults to true when running the app

2021-01-22 17:10 UTC, JackMead approved these changes
The tests work locally now following the readme, and the Travis build still runs the tests successfully, so this looks good.

It looks like you don't use the DONT_CHECK_FOR_TRELLO_LIST_IDS variable any more, so you could remove that from `travis.yml` too, but it doesn't cause any harm so no need to re-review before merging.

2021-01-29 14:10 UTC, merged